apiVersion: v1
kind: Service
metadata:
  name: finalproj-campgrounds-api
  # namespace: my-namespace
  labels:
    app: finalproj-campgrounds-api
spec:
  selector:
    app: finalproj-campgrounds-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
